sendPreparedSqlExecution.url=http://127.0.0.1:29892/pts/dbExecution/receivePreparedSqlExecution
sendSqlExecution.url=http://127.0.0.1:29892/pts/dbExecution/receiveSqlExecution
sendDbConfig.url=http://127.0.0.1:29892/pts/dbExecution/receiveDbConfig
sendHttpRequest.url=http://127.0.0.1:29892/pts/httpExecution/receiveHttpRequest
sendHttpResponse.url=http://127.0.0.1:29892/pts/httpExecution/receiveHttpResponse
sqlWriter.impl=cn.addenda.porttrail.agent.writer.sql.AgentRemoteSqlWriter,cn.addenda.porttrail.agent.writer.sql.AgentLogSqlWriter
sqlWriter.hashSlotCount=8
sqlWriter.dbExecutionQueue.size=8192
httpWriter.impl=cn.addenda.porttrail.agent.writer.http.AgentRemoteHttpWriter,cn.addenda.porttrail.agent.writer.http.AgentLogHttpWriter
httpWriter.hashSlotCount=4
httpWriter.httpExecutionQueue.size=8192
httpWriter.request.maxBodyLength=512
httpWriter.response.maxBodyLength=512
httpFacade.impl=cn.addenda.porttrail.link.http.PortTrailLinkHttpFacadeImpl
jsonFacade.impl=cn.addenda.porttrail.link.json.PortTrailLinkJsonFacadeImpl
logFacade.impl=cn.addenda.porttrail.link.log.PortTrailLinkLogFacadeImpl