package cn.addenda.porttrail.jdbc.core;

import cn.addenda.porttrail.jdbc.bo.PortTrailStatementAttachment;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * @author addenda
 * @since 2024/8/24 17:20
 */
public class PortTrailStatement extends AbstractPortTrailStatement<Statement, PortTrailStatementAttachment> {

  public PortTrailStatement(Statement delegate, PortTrailConnection portTrailConnection) {
    super(delegate, portTrailConnection);
    this.portTrailStatementSqlAttachment = new PortTrailStatementAttachment(getExecutionQueue(), getDataSourcePortTrailId(), getConnectionPortTrailId(), getPortTrailId());
  }

  @Override
  public ResultSet executeQuery(String sql) throws SQLException {
    long start = curMills();
    ResultSet resultSet = delegate.executeQuery(sql);
    executeQuery(sql, start);
    return resultSet;
  }

  @Override
  public int executeUpdate(String sql) throws SQLException {
    long start = curMills();
    int r = delegate.executeUpdate(sql);
    executeUpdate(sql, start);
    return r;
  }

  @Override
  public void close() throws SQLException {
    delegate.close();
    closePortTrail();
  }

  @Override
  public void closePortTrail() throws SQLException {
    // execute的数据，已经写入executionQueue了，随着事务的执行会写出去。没有execute的数据会丢失。
    portTrailStatementSqlAttachment.clearBatch();
    getPortTrailConnection().removePortTrailStatement(this);
  }

  @Override
  public boolean execute(String sql) throws SQLException {
    long start = curMills();
    boolean r = delegate.execute(sql);
    execute(sql, start);
    return r;
  }

  @Override
  public void addBatch(String sql) throws SQLException {
    delegate.addBatch(sql);
    portTrailStatementSqlAttachment.addBatchSql(sql);
  }

  @Override
  public void clearBatch() throws SQLException {
    delegate.clearBatch();
    portTrailStatementSqlAttachment.clearBatch();
  }

  @Override
  public int[] executeBatch() throws SQLException {
    long start = curMills();
    int[] r = delegate.executeBatch();
    executeBatchUpdate(start);
    return r;
  }

  @Override
  public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
    long start = curMills();
    int r = delegate.executeUpdate(sql, autoGeneratedKeys);
    executeUpdate(sql, start);
    return r;
  }

  @Override
  public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
    long start = curMills();
    int r = delegate.executeUpdate(sql, columnIndexes);
    executeUpdate(sql, start);
    return r;
  }

  @Override
  public int executeUpdate(String sql, String[] columnNames) throws SQLException {
    long start = curMills();
    int r = delegate.executeUpdate(sql, columnNames);
    executeUpdate(sql, start);
    return r;
  }

  @Override
  public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
    long start = curMills();
    boolean r = delegate.execute(sql, autoGeneratedKeys);
    execute(sql, start);
    return r;
  }

  @Override
  public boolean execute(String sql, int[] columnIndexes) throws SQLException {
    long start = curMills();
    boolean r = delegate.execute(sql, columnIndexes);
    execute(sql, start);
    return r;
  }

  @Override
  public boolean execute(String sql, String[] columnNames) throws SQLException {
    long start = curMills();
    boolean r = delegate.execute(sql, columnNames);
    execute(sql, start);
    return r;
  }

  @Override
  public long[] executeLargeBatch() throws SQLException {
    long start = curMills();
    long[] r = delegate.executeLargeBatch();
    executeBatchUpdate(start);
    return r;
  }

  @Override
  public long executeLargeUpdate(String sql) throws SQLException {
    long start = curMills();
    long r = delegate.executeLargeUpdate(sql);
    executeUpdate(sql, start);
    return r;
  }

  @Override
  public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
    long start = curMills();
    long r = delegate.executeLargeUpdate(sql, autoGeneratedKeys);
    executeUpdate(sql, start);
    return r;
  }

  @Override
  public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException {
    long start = curMills();
    long r = delegate.executeLargeUpdate(sql, columnIndexes);
    executeUpdate(sql, start);
    return r;
  }

  @Override
  public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException {
    long start = curMills();
    long r = delegate.executeLargeUpdate(sql, columnNames);
    executeUpdate(sql, start);
    return r;
  }

}
